### ISSUE TITLE
Testing errors for search module

### ISSUE THREAD

**Issue by hayleyavw** [uccser/cs-unplugged#1024]
`FileExistsError` is being raised for ~18 tests in the search view.
Apparently this doesn't happen on Travis.

```
ERROR: test_search_view_with_no_query_with_no_index (tests.search.views.test_index_view.IndexViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cs-unplugged/csunplugged/tests/search/views/test_index_view.py", line 22, in setUp
    makedirs(settings.SEARCH_INDEX_PATH)
  File "/docker_venv/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'temp/tests/search/'
```

**Comment by courtneycb** [comment]
Closing as this is no longer happening.
